backend:
  name: github
  repo: martijnvdbrug/schoonheidssalonhelmich.nl

media_folder: "static/img"
public_folder: "/img"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Algemene gegevens"
        name: "global"
        file: "data/global.json"
        fields:
          - {label: Telefoonnummer, name: telefoon, widget: string}