backend:
  name: git-gateway
  repo: martijnvdbrug/schoonheidssalonhelmich.nl
  branch: master

media_folder: "static/img"
public_folder: "/img"

collections:
  - label: "Hoofdpagina's"
    name: "paginas"
    editor:
      preview: false
    files:
      - label: "Algemene gegevens"
        name: "global"
        file: "src/data/global.json"
        fields:
          - {label: Telefoonnummer, name: telefoon, widget: string}
          - {label: Telefoonnummer weergave, name: telefoonDisplay, widget: string}
          - {label: Emailadres, name: email, widget: string}
          - {label: Facebook link, name: facebook, widget: string}
          - {label: Straat en huisnummer, name: straat, widget: string}
          - {label: Postcode en plaats, name: postcodePlaats, widget: string}
          - {label: Afsprakenplanner link, name: afspraakPlanner, widget: string}
          - {label: Footer melding, name: footerBanner, widget: string}
          - {label: Footer melding link, name: footerBannerLink, widget: string}
          - label: "Openingstijden"
            name: openinghours
            collapsed: true
            allow_add: false
            widget: "list"
            fields:
              - { label: Dag, name: day, widget: string }
              - { label: Uren, name: hours, widget: string }
      - label: "Home pagina"
        name: "home"
        file: "src/data/home.json"
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Text, name: body, widget: text }
          - { label: Banner afbeelding, name: image, widget: image }
          - label: "afbeeldingen"
            name: blocks
            collapsed: true
            allow_add: false
            widget: "list"
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Link, name: link, widget: string }
              - { label: Afbeelding, name: image, widget: image }
      - label: "Gezichtsbehandelingen"
        name: "gezichtsbehandelingen"
        file: "src/data/gezichtsbehandeling.json"
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Text, name: body, widget: text }
          - label: "afbeeldingen"
            name: blocks
            collapsed: true
            allow_add: false
            widget: "list"
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Link, name: link, widget: string }
              - { label: Afbeelding, name: image, widget: image }
      - label: "Huidverbeterende gezichtsbehandeling"
        name: "huidverbeterend"
        file: "src/data/huidverbeterend.json"
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Text, name: body, widget: text }
          - label: "afbeeldingen"
            name: blocks
            collapsed: true
            allow_add: false
            widget: "list"
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Link, name: link, widget: string }
              - { label: Afbeelding, name: image, widget: image }
      - label: "Henna wenkbrauwen"
        name: "Voetreflex"
        file: "src/data/voetreflex.json"
        create: false
        identifier_field: name
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Text, name: body, widget: text }
          - { label: Banner afbeelding, name: image, widget: image }
          - label: "Gallery"
            name: "images"
            widget: "list"
            collapsed: true
            allow_add: true
            field: { label: Image, name: image, widget: image }
      - label: "Over ons"
        name: "about"
        file: "src/data/over-ons.json"
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Text, name: body, widget: text }
          - label: "Werknemers"
            name: employees
            collapsed: true
            allow_add: true
            widget: "list"
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: body, widget: text }
              - { label: Afbeelding, name: image, widget: image }
      - label: "Tarieven"
        name: "tarieven"
        file: "src/data/tarieven.json"
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Text, name: body, widget: text }
          - label: "Category"
            name: categories
            collapsed: true
            allow_add: true
            widget: "list"
            fields:
              - { label: Titel, name: title, widget: string }
              - label: "Behandelingen"
                name: items
                collapsed: true
                allow_add: true
                widget: "list"
                fields:
                  - { label: Naam, name: name, widget: string}
                  - { label: Prijs, name: price, widget: string}
                  - { label: Link, name: link, widget: string, required: false}
  - label: "Subpagina's"
    name: "subpages"
    folder: "src/data/subpages"
    editor:
      preview: false
    create: false
    identifier_field: name
    extension: json
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Text, name: body, widget: text }
      - { label: Banner afbeelding, name: image, widget: image }
      - label: "Gallery"
        name: "images"
        widget: "list"
        collapsed: true
        allow_add: true
        field: { label: Image, name: image, widget: image }
