backend:
  name: git-gateway
  repo: martijnvdbrug/schoonheidssalonhelmich.nl
  branch: master

media_folder: "static/img"
public_folder: "/img"

collections:
  - label: "Paginas"
    name: "paginas"
    editor:
      preview: false
    files:
      - label: "Algemene gegevens"
        name: "global"
        file: "src/data/global.json"
        fields:
          - {label: Telefoonnummer, name: telefoon, widget: string}
          - {label: Telefoonnummer weergave, name: telefoonDisplay, widget: string}
          - {label: Emailadres, name: email, widget: string}
          - {label: Facebook link, name: facebook, widget: string}
          - {label: Straat en huisnummer, name: straat, widget: string}
          - {label: Postcode en plaats, name: postcodePlaats, widget: string}
          - {label: Afsprakenplanner link, name: afspraakPlanner, widget: string}
      - label: "Home pagina"
        name: "home"
        file: "src/data/home.json"
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Text, name: body, widget: text }
          - label: "afbeeldingen"
            name: blocks
            collapsed: false
            allow_add: false
            widget: "list"
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Link, name: link, widget: string }
              - { label: Afbeelding, name: image, widget: image }